### ISSUE TITLE
Error on Migration: wrong number of arguments (given 2, expected 1)/usr/local/bundle/gems/highline-1.7.10/lib/highline.rb:620:in `say'

### ISSUE THREAD

**Issue by Rovel** [scenic-views/scenic#253]
Hi,

I'm trying to run a basic migration:

```
def change
    update_view :materialized_skill_table_name,
      version: 2,
      revert_to_version: 1,
      materialized: true
  end
```

and it trows this strange error:

```
wrong number of arguments (given 2, expected 1)/usr/local/bundle/gems/highline-1.7.10/lib/highline.rb:620:in `say'
/usr/local/bundle/gems/scenic-1.3.0/lib/scenic/adapters/postgres/index_reapplication.rb:66:in `say'
/usr/local/bundle/gems/scenic-1.3.0/lib/scenic/adapters/postgres/index_reapplication.rb:48:in `try_index_create'
/usr/local/bundle/gems/scenic-1.3.0/lib/scenic/adapters/postgres/index_reapplication.rb:35:in `each'
/usr/local/bundle/gems/scenic-1.3.0/lib/scenic/adapters/postgres/index_reapplication.rb:35:in `on'
/usr/local/bundle/gems/scenic-1.3.0/lib/scenic/adapters/postgres.rb:154:in `update_materialized_view'
/usr/local/bundle/gems/scenic-1.3.0/lib/scenic/statements.rb:86:in `update_view'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:846:in `block in method_missing'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:815:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:815:in `say_with_time'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:835:in `method_missing'
/app/db/migrate/20170315164338_update_materialized_skill_reports_to_version_2.rb:3:in `change'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:789:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:771:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration/compatibility.rb:121:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:951:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `each'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1150:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:1006:in `up'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/migration.rb:990:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/tasks/database_tasks.rb:163:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/usr/local/bundle/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/usr/local/bundle/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'

```

**Comment by Rovel** [comment]
I looks like there's some relation with materialised views with index when you call update_view on them

**Comment by tangens** [comment]
i have the same strange issue with `create_view`

**Comment by derekprior** [comment]
This sounds like an issue with highline, perhaps? `say` as defined in `ActiveRecord::Migration` takes 2 arguments. The issue title indicates that for some reason, scenic is hitting the `say` defined by highline.

**Comment by al** [comment]
Apologies for dragging up old issues but we're having the same problem (not using Highline or anything though).

Tracing it through, [no `speaker` is explicitly passed](https://github.com/scenic-views/scenic/blob/cecb1b3f3bb98b924565c81718abcac9a868ee49/lib/scenic/adapters/postgres.rb#L166), so the `speaker` is [defaulting to ActiveRecord::Migration](https://github.com/scenic-views/scenic/blob/cecb1b3f3bb98b924565c81718abcac9a868ee49/lib/scenic/adapters/postgres/index_reapplication.rb#L16) (the class), but AFAICT there is no `say` class method there, only an [instance method](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb).

Consequently `say` seems to be ultimately delegated to [rubygems/user_interaction.rb#L151](https://github.com/rubygems/rubygems/blob/3e0641a6c8eff4d9a5d26856b1ac7417168b4cc0/lib/rubygems/user_interaction.rb#L151), i.e. you can _fix_ the problem by changing its signature, but that's clearly not right.

For now we're just monkey patching our way around it but would love to get to the bottom of it. Will try replicate it in a minimal app when I have a chance.

**Comment by rapito** [comment]
@derekprior this is a nexisting issue still on latest version. 
@al describes the issue that's happening correctly.

To shed some more light into it:
```
      def update_materialized_view(name, sql_definition, no_data: false)
        raise_unless_materialized_views_supported

        IndexReapplication.new(connection: connection).on(name) do
          drop_materialized_view(name)
          create_materialized_view(name, sql_definition, no_data: no_data)
        end
      end
```
Then in here you can clearly see that speaker.say would evaluate `ActiveRecord::Migration.say` :
```
      class IndexReapplication
        # Creates the index reapplication object.
        #
        # @param connection [Connection] The connection to execute SQL against.
        # @param speaker [#say] (ActiveRecord::Migration) The object used for
        #   logging the results of reapplying indexes.
        def initialize(connection:, speaker: ActiveRecord::Migration)
          @connection = connection
          @speaker = speaker
        end
        
        def say(message)
          subitem = true
          speaker.say(message, subitem)
        end
      end
```

However, it is not a class method but an instance method as it was very well described by Al.

**Comment by derekprior** [comment]
Reopened. Sounds like it should be a straightforward patch to instantiate the speaker in the default arguments. 

Patches welcome.

**Comment by rapito** [comment]
> Reopened. Sounds like it should be a straightforward patch to instantiate the speaker in the default arguments.
> 
> Patches welcome.

Done :B

**Comment by ClaudioFloreani** [comment]
I get the same error when migrating down a standard SQL view (with model, but it's unchanged).

Nothing strange in the migration file (auto generated by `rails generate scenic:view Campaign`):

    class UpdateCampaignsToVersion3 < ActiveRecord::Migration[6.1]
      def change
        update_view :campaigns, version: 3, revert_to_version: 2
      end
    end

and nothing strange in the SQL views (it's a SELECT with several JOINS but I added in just a few attributes without changing the resulting table), for reference, here's the diff:

```
diff db/views/campaigns_v02.sql db/views/campaigns_v03.sql 

2,3c2
<   o.number AS "number",
<   t.collection,
---
>   s.brand,
4a4,7
>   s.campaign,
>   t.collection,
>   o.number AS "number",
>   c.status AS "role",
6,8d8
<   a.city,
<   a.country,
<   p.status AS "purchase",
9a10,11
>   p.status AS "purchase",
>   t.status AS "production",
10a13,15
>   a.country,
>   a.city,
>   t.code,
13,14c18,20
<   ps.qty,
<   t.cost_cents AS "lab_cost",
---
>   s.flavors->>'color' AS "flavor_mix",
>   o.id AS "oid",
>   o.cost_cents AS "sell_fee",
18,19c24,26
<   o.id AS "oid",
<   o.cost_cents AS "sell_fee",
---
>   t.id AS "tid",
>   ps.qty,
>   t.cost_cents AS "lab_cost",

```

No problem migrating up, but if I try to redo the migration with `rake db:migrate:redo` (or `rake db:rollback`) it fails with:

```
== 20211020121227 UpdateCampaignsToVersion3: reverting ========================
-- update_view(:campaigns, {:version=>2})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 2, expected 1)
/Users/fluoro/.rvm/gems/ruby-3.0.0/gems/scenic-1.5.4/lib/scenic/statements.rb:91:in `update_view'
/Users/fluoro/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:929:in `block in method_missing'
/Users/fluoro/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:897:in `block in say_with_time'
/Users/fluoro/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:897:in `say_with_time'
/Users/fluoro/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:918:in `method_missing'
…

```
