### ISSUE TITLE
Migration fails in Heroku

### ISSUE THREAD

**Issue by moveson** [scenic-views/scenic#304]
Scenic is working for me locally, but when I deploy to Heroku and attempt to run migrations, it fails with the following error:
```
== 20200801232418 CreateEffortSegments: migrating =============================
-- create_view(:effort_segments, {:materialized=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

No such file or directory @ rb_sysopen - /app/db/views/effort_segments_v01.sql
/app/vendor/bundle/ruby/2.6.0/gems/scenic-1.5.2/lib/scenic/definition.rb:10:in `read'
/app/vendor/bundle/ruby/2.6.0/gems/scenic-1.5.2/lib/scenic/definition.rb:10:in `to_sql'
/app/vendor/bundle/ruby/2.6.0/gems/scenic-1.5.2/lib/scenic/statements.rb:152:in `definition'
/app/vendor/bundle/ruby/2.6.0/gems/scenic-1.5.2/lib/scenic/statements.rb:37:in `create_view'
```
It appears that the SQL the migration needs in order to execute is not available when it is needed.

This is a blocker for me; I'm pretty much married to Heroku at this point. Would love to know how I can get past this.

**Comment by moveson** [comment]
This was caused by a stupid error on my part. I had a global gitignore for `.sql` files, which meant my file wasn't committed to the repo. :facepalm:
